css selectors
KarenCelis/cypress-training pull request #7
Opened 2021-03-26 01:19 UTC by KarenCelis

2021-03-26 01:34 UTC, holgiosalos commented on buy-shirt.spec.ts
> +
delete spaces in line 19

2021-03-26 02:09 UTC, renardete commented
If the PR is not ready, you could convert it to draft PR.

2021-03-28 00:13 UTC, holgiosalos requested changes
Please locate the `buy-shirt.spec.ts` file in the `cypress/integration` folder.

2021-03-28 00:13 UTC, holgiosalos commented on buy-shirt.spec.ts
> +    // Debes completar la prueba ...
In this step the idea is to complete the missing steps to have a successful execution, check message on slack:
https://psl-techtalks.slack.com/archives/C01QA81V29F/p1616800059027300

![image](https://user-images.githubusercontent.com/10209180/112738375-645dc080-8f30-11eb-8241-8719e1f2115e.png)

2021-03-30 14:44 UTC, holgiosalos approved these changes
Awesome job!

2021-03-30 15:44 UTC, merged